
CSX:
  company_name: Chevron
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\test_folder_KO"

LEG:
  company_name: Legget and platt
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\test_folder_LEG"