MC.PA:
  company_name: LVMH Moët Hennessy
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

LOW:
  company_name: LOWE'S COS INC
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

HRB:
  company_name: H&R Block, Inc.
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

HD:
  company_name: HOME DEPOT
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"  

PKG:
  company_name: PACKAGING CORP OF AMERICA
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

BBY:
  company_name: Best Buy Co., Inc.
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

MGA:
  company_name: MAGNA INTERNATIONAL INC
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

SBUX:
  company_name: STARBUCKS CORP
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

GPC:
  company_name: GENUINE PARTS CO
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

LCII:
  company_name: LCI INDUSTRIES
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

SON:
  company_name: SONOCO PRODUCTS CO
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"

AW-UN.TO:
  company_name: A-W-REVENUE-ROYALTIES-INC-1409116
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\cyclical"