
# Energy 
CSX:
  company_name: Chevron
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\energy"

PSX:
  company_name: Phillips 66
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\energy"

WMB:
  company_name: Williams Company
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\energy"

XOM:
  company_name: Exxon
  path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\energy"

# # Health
# ABBV:
#   company_name: Abbvie
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# BMY:
#   company_name: Bristol Myiers
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# DGX:
#   company_name: Quest Diagnosis
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# GILD:
#   company_name: Gilead Science
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# JNJ:
#   company_name: Jonhson and Jonhson
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# MDT:
#   company_name: Medtronic
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# PRGO:
#   company_name: Perrigo
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\health"

# EMR:
#   company_name: Emerson Electrics
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\Industry"

# FTT.TO:
#   company_name: Finnies
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\Industry"

# HON:
#   company_name: Honeywell
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\Industry"

# MMM:
#   company_name: 3M
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\Industry"
 
# NSC:
#   company_name: Norfolk Southern
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\Industry"  

# SWK:
#   company_name: Stanley Black
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\Industry"  

# # Real estate
# VICI:
#   company_name: VICI property 
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# AMT:
#   company_name: American Tower
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# CUBE:
#   company_name: CubeSmart
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# EGP:
#   company_name: EastGroup Properties
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# ESS:
#   company_name: Essec Property
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# EXR:
#   company_name: Extra Space storage
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# FRT:
#   company_name: Federal Realty Investment
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# INVH:
#   company_name: Invitation homes
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# MAA:
#   company_name: Mid america apartment
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# NSA:
#   company_name: NATIONAL STORAGE AFFILIATES TRUST
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# REXR:
#   company_name: Rexford Industrials
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\real_estate"

# # Telecom
# VZ:
#   company_name: Verizon
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\telecom"

# BCE:
#   company_name: BCE Inc
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\telecom"

# CCOI:
#   company_name: Cogent Communication
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\telecom"

# CMCSA:
#   company_name: Comcast Corporation
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\telecom"

# T:
#   company_name: AT&T
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\telecom"

# # Utilities
# ARTNA:
#   company_name: ARTESIAN RESOURCES CORPORATION
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"

# AWK:
#   company_name: American Water work
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"

# AWR:
#   company_name: American State Water
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"

# CWT:
#   company_name: California Water Service
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"

# GWRS:
#   company_name: GLOBAL WATER RESOURCES, INC.
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"

# SJW:
#   company_name: SJW group
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"

# WTRG:
#   company_name: Essential utilities
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\utilities"


# # Tech
# HPQ:
#   company_name: HP INC
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# GLW:
#   company_name: CORNING INC
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# GRMN:
#   company_name: GARMIN LTD
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# SWKS:
#   company_name: SKYWORKS SOLUTIONS INC
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# AVT:
#   company_name: AVNET INC
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# CSCO:
#   company_name: Cisco System
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# QCOM:
#   company_name: Qualcomm Inc.
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# AOS:
#   company_name: Amdocs
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"

# PAIX:
#   company_name: Paychex
#   path_to_save: "C:\\Users\\lucas\\OneDrive\\Bureau\\companies_analysis_2024\\tech"
