LYB:
  company_name: LyondellBasell Industries
  path_to_save: "/mnt/c/Users/User/Desktop/analysis_company/material"

APD:
  company_name: Air Product
  path_to_save: "/mnt/c/Users/User/Desktop/analysis_company/material"

PPG:
  company_name: PPG Industries
  path_to_save: "/mnt/c/Users/User/Desktop/analysis_company/material"

DOW:
  company_name: DOW Chemicals
  path_to_save: "/mnt/c/Users/User/Desktop/analysis_company/material"
